[package]
name = "fenrs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
lazy_static = "1.4.0"
nom = "7.1.3"
ratatui = "0.26.2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "warn"
