[package]
name = "fenrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
lazy_static = "1.4.0"
nom = "7.1.3"
ratatui = "0.24.0"
