name: Run tests

on: push

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1

      - name: Test with cargo
        run: cargo test
